---
kind: Namespace
apiVersion: v1
metadata:
  name: exporter
  labels:
    name: exporter

---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXR...
kind: Secret
metadata:
  name: github-token
  namespace: exporter
type: kubernetes.io/dockerconfigjson

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: exporter
  name: redfish-exporter
  labels:
    name: redfish-exporter
    app: redfish-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redfish-exporter
  template:
    metadata:
      labels:
        app: redfish-exporter
    spec:
      imagePullSecrets:
      - name: github-token
      containers:
      - image: ghcr.io/svtechnmaa/redfish-exporter:latest
        name: physical-exporter
        imagePullPolicy: Always
        ports:
        - containerPort: 9814
          protocol: TCP
          name: red-ex-port
        volumeMounts:
        - name: redfish-configs
          mountPath: "/opt/redfish_exporter/templates/configs"
      volumes:
      - name: redfish-configs
        configMap:
          name: redfish-configs
          items:
          - key: "inventory.yml"
            path: "inventory.yml"
          - key: "sample.yml"
            path: "sample.yml"

---
apiVersion: v1
kind: Service
metadata:
  namespace: exporter
  name: redfish-exporter
  labels:
    name: redfish-exporter
spec:
  selector:
    app: redfish-exporter
  ports:
    - name: red-ex-port
      protocol: TCP
      port: 9814
      targetPort: 9814
  type: ClusterIP
