version: 1
disable_existing_loggers: False
formatters:
  default:
    # "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s [%(levelname)s] %(message)s'
  access:
    # "()": uvicorn.logging.AccessFormatter
    format: '%(asctime)s [%(levelname)s] %(message)s'
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  defaultfile:
    formatter: default
    class: logging.FileHandler
    filename: /tmp/app.log
  # access:
  #   formatter: access
  #   class: logging.StreamHandler
  #   stream: ext://sys.stdout
  accessfile:
    formatter: access
    class: logging.FileHandler
    filename: /tmp/access.log
  
loggers:
  uvicorn.error:
    level: DEBUG
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: DEBUG
    handlers:
      - accessfile
    propagate: no
  root:
    level: INFO
    handlers:
      - default
      - defaultfile
    propagate: no