name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: '${{ github.actor }}'
        password: '${{ secrets.GITHUB_TOKEN }}'
    - name: Build and Push specific version
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/redfish-exporter:1.0.x
          ghcr.io/${{ github.repository_owner }}/redfish-exporter:1.0.${{ github.run_number }}
          ghcr.io/${{ github.repository_owner }}/redfish-exporter:latest
        build-args: |
          appVersion=1.0.${{ github.run_number }}
          maintainer=Freezing