name: CI
on:
  push:
    branches:
      - main
    tags:
    - '1.*'
  pull_request:
    branches:
      - main

jobs:
  build_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Images
      run: docker buildx build -t ghcr.io/${{ github.repository_owner }}/redfish-exporter:v1.0.${{ github.run_number }} .
    - name: Cache outputs
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Tag specific version
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/redfish-exporter
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: '${{ github.actor }}'
        password: '${{ secrets.GITHUB_TOKEN }}'
    - name: Push specific version
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/redfish-exporter:{{version}}
          ghcr.io/${{ github.repository_owner }}/redfish-exporter:{{major}}.{{minor}}