name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Images
      run: docker buildx build -t redfish-exporter:latest .
    - name: Cache outputs
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: '${{ github.actor }}'
        password: '${{ secrets.GITHUB_TOKEN }}'
    - name: Push image to GitHub Container Registry
      run: |
        docker tag redfish-exporter:latest ghcr.io/${{ github.repository_owner }}/${{ env.REPO }}:v1.${{ github.run_number }}
        docker tag redfish-exporter:latest ghcr.io/${{ github.repository_owner }}/${{ env.REPO }}:latest
        docker push ghcr.io/${{ github.repository_owner }}/${{ env.REPO }}:v1.${{ github.run_number }}
        docker push ghcr.io/${{ github.repository_owner }}/${{ env.REPO }}:latest
